### ISSUE TITLE
Simple typographical error 

### ISSUE THREAD

**Issue by nnamdi16** [phalconVee/laravel-paga#4]
1. Prerequisites
Confirm that your server can conclude a TLSv1.2 connection to Paga's servers. Most up-to-date software have theis capability. Contact your service provider for guidance if you have any SSL errors. Don't disable SSL peer verification!

The short read below has a grammatical error where you have "theis", it ought to be this

**Comment by phalconVee** [comment]
Oops!! Thanks.

**Comment by nnamdi16** [comment]
Welcome boss, you did a great job. I have been testing your work so that we
can adopt it in my team.

Warm regards,

Nwabuokei Nnamdi

**Comment by phalconVee** [comment]
Thank you so much. I appreciate.
