### ISSUE TITLE
moneyTransferBulk() returns only one successful transaction

### ISSUE THREAD

**Issue by nnamdi16** [phalconVee/laravel-paga#5]
moneyTransferBulk ought to return all transactions successfully or all transaction failed. This depends on the funds in the account of the sender and the amount to be sent to the receiver. But in the case of the implementation, it appears it is only picking one transaction and executing it. So I took the luxury of checking other libraries such as the PHP business API library, I discovered it was able to execute all the transactions successfully as against the laravel library. You may have to look into it.

Response from the laravel library
`(
    [responseCode] => 1
    [message] => Partial successful bulk money transfer. 1 successful, 1 items failed out of 2
    [bulkReferenceNumber] => bulk-EDYXLSUDLLFYUZFC24LWH764U
    [results] => Array
        (
            [0] => Array
                (
                    [responseCode] => 0
                    [message] => You have successfully sent N600.00 to 08030408527. Paga Txn ID: JG6XZ. Thank you for using Paga!
                    [referenceNumber] => EDYXLSUDLLFYUZFC24LWH764U
                    [withdrawalCode] => 
                    [transactionId] => JG6XZ
                    [fee] => 150
                    [receiverRegistrationStatus] => REGISTERED
                    [currency] => NGN
                    [exchangeRate] => 
                )

            [1] => Array
                (
                    [responseCode] => 
                    [message] => 
                    [referenceNumber] => EDYXLSUDLLFYUZFC24LWH764U
                    [withdrawalCode] => 
                    [transactionId] => 
                    [fee] => 
                    [receiverRegistrationStatus] => 
                    [currency] => 
                    [exchangeRate] => 
                )

        )

)`

Response from the PHP library
`[2021-02-22T22:04:27.919364+00:00] stderr.INFO: response: [{"responseCode":0,"message":"Successful bulk money transfer. 2 of 2 items successful","bulkReferenceNumber":"60342a68aaa74","results":[{"responseCode":0,"message":"You have successfully sent N1,000.00 to 07038276158. Paga Txn ID: N77L3. Thank you for using Paga!","referenceNumber":"60342a68aaa06","withdrawalCode":null,"transactionId":"N77L3","fee":150.0,"receiverRegistrationStatus":"REGISTERED","currency":"NGN","exchangeRate":null},{"responseCode":0,"message":"You have successfully sent N1,000.00 to 07038276158. Paga Txn ID: MJ972. Thank you for using Paga!","referenceNumber":"60342a68aaa07","withdrawalCode":null,"transactionId":"MJ972","fee":150.0,"receiverRegistrationStatus":"REGISTERED","currency":"NGN","exchangeRate":null}]}] []
{"responseCode":0,"message":"Successful bulk money transfer. 2 of 2 items successful","bulkReferenceNumber":"60342a68aaa74","results":[{"responseCode":0,"message":"You have successfully sent N1,000.00 to 07038276158. Paga Txn ID: N77L3. Thank you for using Paga!","referenceNumber":"60342a68aaa06","withdrawalCode":null,"transactionId":"N77L3","fee":150.0,"receiverRegistrationStatus":"REGISTERED","currency":"NGN","exchangeRate":null},{"responseCode":0,"message":"You have successfully sent N1,000.00 to 07038276158. Paga Txn ID: MJ972. Thank you for using Paga!","referenceNumber":"60342a68aaa07","withdrawalCode":null,"transactionId":"MJ972","fee":150.0,"receiverRegistrationStatus":"REGISTERED","currency":"NGN","exchangeRate":null}]}%`

**Comment by phalconVee** [comment]
Hi Nnamdi, 

Kindly pass different references in each transfer block instead of using the same reference per transfer block when consuming the **moneyTransferBulk** endpoint.

The API is probably treating each block as a single transfer request (as a result of passing the same reference) that is why only one of the transfer is successful.

The SAMPLES.md file has been updated to reflect this change for test purposes.

**Comment by nnamdi16** [comment]
There are actually two different reference numbers for each transaction. The first transaction has a reference number of `60342a68aaa06` while the second has a reference number of `60342a68aaa07`. You may see some repetition, if you look closely the response was printed twice, it doesn't mean it was using the same reference number.

**Comment by phalconVee** [comment]
```
$items = [
        [
            'referenceNumber' => "TNXID_".Paga::getTransactionReference(),
             ....
         ],
        [
            'referenceNumber' => "TNXID_".Paga::getTransactionReference(),
             ....
        ]
];
```

Ensure the `refereceNumber` is unique in each transfer block.
